/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.UIManager;

/**
 *
 * @author LUCYLEONOR
 */
public class PanelSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PanelSeleccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdAdmin = new javax.swing.JButton();
        cmdVisitante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caribbean To World");
        setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 224, 614, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de sesion");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        cmdAdmin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdAdmin.setForeground(new java.awt.Color(255, 255, 255));
        cmdAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Admin.png"))); // NOI18N
        cmdAdmin.setText("Administrador");
        cmdAdmin.setBorder(null);
        cmdAdmin.setBorderPainted(false);
        cmdAdmin.setContentAreaFilled(false);
        cmdAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        cmdAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdAdmin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cmdAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdminActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 100));

        cmdVisitante.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdVisitante.setForeground(new java.awt.Color(255, 255, 255));
        cmdVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Visitor.png"))); // NOI18N
        cmdVisitante.setText("Visitante");
        cmdVisitante.setBorder(null);
        cmdVisitante.setBorderPainted(false);
        cmdVisitante.setContentAreaFilled(false);
        cmdVisitante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdVisitante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdVisitante.setIconTextGap(20);
        cmdVisitante.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cmdVisitante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVisitanteActionPerformed(evt);
            }
        });
        jPanel3.add(cmdVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 120, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tambores.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 250));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        setSize(new java.awt.Dimension(454, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdminActionPerformed

        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_cmdAdminActionPerformed

    private void cmdVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVisitanteActionPerformed

        PrincipalVisitante pv = new PrincipalVisitante();
        pv.setVisible(true);
        dispose();
    }//GEN-LAST:event_cmdVisitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/ UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdmin;
    private javax.swing.JButton cmdVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
